export type Property = {
  _id: string;
  title: string;
  price: number;
  currency: string;
  location: string;
  address: string;
  beds: number;
  baths: number;
  sqft: number;
  images: { url: string }[];
  offerCategory?: "none" | "dashain" | "latest" | "hot" | "limited_time";
  offerTitle?: string;
  offerDescription?: string;
  offerBadge?: string;
  offerDiscountType?: "none" | "percentage" | "fixed";
  offerDiscountValue?: number;
  offerValidUntil?: string | null;
  offerActive?: boolean;
};
